stages:
  - deploy

deploy:
  image: alpine:latest
  stage: deploy
  tags:
    - deployment
  before_script:
    - apk add --no-cache openssh-client
    - chmod og= $ID_RSA
  script:
    # SSH into the server, pull the latest code, and deploy using Docker Compose
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "
      cd /home/ubuntu/collegram &&
      git pull https://$GIT_USERNAME:$GIT_PASSWORD@hamgit.ir/rc-dev-1403/co-peper/collegram  &&
      cd .. &&
      docker compose -f docker-compose-prod.yml down &&
      docker compose -f docker-compose-prod.yml build &&
      docker compose -f docker-compose-prod.yml up -d --remove-orphans"
  environment:
    name: production
    url: http://188.213.197.231 
  only:
    - main
